export const NFL_TEAM_DIVISIONS: Record<string, "East" | "North" | "South" | "West"> = {
  BUF: "East",
  MIA: "East",
  NE: "East",
  NYJ: "East",
  BAL: "North",
  CIN: "North",
  CLE: "North",
  PIT: "North",
  HOU: "South",
  IND: "South",
  JAX: "South",
  TEN: "South",
  DEN: "West",
  KC: "West",
  LAC: "West",
  LV: "West",
  DAL: "East",
  NYG: "East",
  PHI: "East",
  WSH: "East",
  CHI: "North",
  DET: "North",
  GB: "North",
  MIN: "North",
  ATL: "South",
  CAR: "South",
  NO: "South",
  TB: "South",
  ARI: "West",
  LAR: "West",
  SEA: "West",
  SF: "West",
};

export default { NFL_TEAM_DIVISIONS };
