import AdminSectionCard from "@/components/admin/AdminSectionCard";
import AdminStatCard from "@/components/admin/AdminStatCard";
import { getAdminPicksData } from "@/lib/admin";

function formatDate(value: string) {
  return new Date(`${value}T12:00:00`).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function formatPercent(value: number) {
  return `${value.toFixed(1)}%`;
}

function formatOdds(value: number) {
  return value > 0 ? `+${value}` : `${value}`;
}

function formatEdge(value: number) {
  const pct = Math.abs(value) <= 1 ? value * 100 : value;
  return `${pct > 0 ? "+" : ""}${pct.toFixed(1)}%`;
}

export default async function AdminPicksPage() {
  const data = await getAdminPicksData();

  return (
    <div className="space-y-6">
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <AdminStatCard label="Total Picks" value={data.totalPicks} meta="Stored across all dates" tone="blue" />
        <AdminStatCard label="Resolved" value={data.resolved} meta={`${data.pending} still pending`} tone="green" />
        <AdminStatCard label="Win Rate" value={formatPercent(data.winPct)} meta={`${data.wins}-${data.losses}-${data.pushes} record`} tone="yellow" />
        <AdminStatCard
          label="Net Units"
          value={`${data.netUnits > 0 ? "+" : ""}${data.netUnits}u`}
          meta="One unit per tracked pick"
          tone={data.netUnits >= 0 ? "green" : "red"}
        />
      </section>

      <AdminSectionCard
        title="Running Win Percentage"
        description="Cumulative win rate over resolved picks. Pick history populates when the daily pick APIs are requested."
      >
        {data.runningWinPct.length === 0 ? (
          <p className="text-sm text-gray-400">No server-side pick history has been recorded yet.</p>
        ) : (
          <div className="space-y-3">
            {data.runningWinPct.map((point) => (
              <div key={point.date} className="grid gap-2 md:grid-cols-[120px_1fr_88px_90px] md:items-center">
                <p className="text-sm text-gray-400">{formatDate(point.date)}</p>
                <div className="h-3 overflow-hidden rounded-full bg-dark-bg">
                  <div
                    className="h-full rounded-full bg-[linear-gradient(90deg,#4a9eff_0%,#22c55e_100%)]"
                    style={{ width: `${Math.max(point.winPct, point.resolved > 0 ? 4 : 0)}%` }}
                  />
                </div>
                <p className="text-sm font-semibold text-white">{formatPercent(point.winPct)}</p>
                <p className="text-xs uppercase tracking-[0.16em] text-gray-500">{point.resolved} decided</p>
              </div>
            ))}
          </div>
        )}
      </AdminSectionCard>

      <AdminSectionCard
        title="Daily Breakdown"
        description="Wins, losses, pushes, and pending picks by date."
      >
        <div className="overflow-x-auto">
          <table className="min-w-full text-left text-sm">
            <thead className="text-xs uppercase tracking-[0.2em] text-gray-500">
              <tr>
                <th className="px-4 py-3">Date</th>
                <th className="px-4 py-3">Total</th>
                <th className="px-4 py-3">W</th>
                <th className="px-4 py-3">L</th>
                <th className="px-4 py-3">Push</th>
                <th className="px-4 py-3">Pending</th>
                <th className="px-4 py-3">Win %</th>
                <th className="px-4 py-3">Net Units</th>
              </tr>
            </thead>
            <tbody>
              {data.dailyBreakdown.map((day, index) => (
                <tr
                  key={day.date}
                  className={index % 2 === 0 ? "bg-dark-bg/40" : "bg-dark-surface/70"}
                >
                  <td className="px-4 py-3 font-medium text-white">{formatDate(day.date)}</td>
                  <td className="px-4 py-3 text-gray-300">{day.total}</td>
                  <td className="px-4 py-3 text-gray-300">{day.wins}</td>
                  <td className="px-4 py-3 text-gray-300">{day.losses}</td>
                  <td className="px-4 py-3 text-gray-300">{day.pushes}</td>
                  <td className="px-4 py-3 text-gray-300">{day.pending}</td>
                  <td className="px-4 py-3 text-gray-300">{formatPercent(day.winPct)}</td>
                  <td className="px-4 py-3 text-gray-300">
                    {day.netUnits > 0 ? "+" : ""}
                    {day.netUnits}u
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </AdminSectionCard>

      <AdminSectionCard
        title="Full Pick History"
        description="Every persisted pick generated by the NHL and NBA pick endpoints."
      >
        <div className="overflow-x-auto">
          <table className="min-w-full text-left text-sm">
            <thead className="text-xs uppercase tracking-[0.2em] text-gray-500">
              <tr>
                <th className="px-4 py-3">Date</th>
                <th className="px-4 py-3">League</th>
                <th className="px-4 py-3">Pick</th>
                <th className="px-4 py-3">Team</th>
                <th className="px-4 py-3">Result</th>
                <th className="px-4 py-3">Odds</th>
                <th className="px-4 py-3">Edge</th>
              </tr>
            </thead>
            <tbody>
              {data.picks.map((pick, index) => (
                <tr
                  key={`${pick.date}-${pick.league}-${pick.id}`}
                  className={index % 2 === 0 ? "bg-dark-bg/40" : "bg-dark-surface/70"}
                >
                  <td className="px-4 py-3 text-gray-300">{formatDate(pick.date)}</td>
                  <td className="px-4 py-3 text-gray-300">{pick.league ?? "NHL"}</td>
                  <td className="px-4 py-3 font-medium text-white">{pick.pickLabel}</td>
                  <td className="px-4 py-3 text-gray-300">{pick.team}</td>
                  <td className="px-4 py-3 text-gray-300">{pick.result}</td>
                  <td className="px-4 py-3 text-gray-300">{formatOdds(pick.odds)}</td>
                  <td className="px-4 py-3 text-gray-300">{formatEdge(pick.edge)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </AdminSectionCard>
    </div>
  );
}
