import { storeDailyPickSlate } from "../src/lib/pick-history-store";
import type { AIPick } from "../src/lib/types";

const date = "2026-04-09";

const picks: AIPick[] = [
  {
    id: "golf-xander-schauffele-tournament-winner-2026-04-09",
    date,
    type: "player",
    playerName: "Xander Schauffele",
    team: "SCH",
    teamColor: "#167c45",
    opponent: "Masters Tournament",
    isAway: false,
    propType: "Tournament Winner",
    line: 0,
    direction: "Over",
    pickLabel: "Xander Schauffele to win",
    edge: 1.4,
    hitRate: 35,
    confidence: 35,
    reasoning: "Xander is the cleanest price-to-profile outright on the board. DataGolf rank #4, elite tee-to-green baseline, and DraftKings +1750 implies 5.4% while the model lands closer to 6.8%. This is the kind of Masters outright you want, proven class with enough number left to justify the swing.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: 1750,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  },
  {
    id: "golf-rory-mcilroy-tournament-winner-2026-04-09",
    date,
    type: "player",
    playerName: "Rory McIlroy",
    team: "MCI",
    teamColor: "#167c45",
    opponent: "Masters Tournament",
    isAway: false,
    propType: "Tournament Winner",
    line: 0,
    direction: "Over",
    pickLabel: "Rory McIlroy to win",
    edge: 0.8,
    hitRate: 32,
    confidence: 32,
    reasoning: "Rory is still one of the few guys with a real win ceiling here, not fake nostalgia bullshit. DataGolf rank #3, model win probability around 7.3%, and DraftKings +1175 implies about 7.8%. Thin edge, but the profile is legit enough for the outright card because his top-end Augusta path is real.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: 1175,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  },
  {
    id: "golf-jon-rahm-tournament-winner-2026-04-09",
    date,
    type: "player",
    playerName: "Jon Rahm",
    team: "RAH",
    teamColor: "#167c45",
    opponent: "Masters Tournament",
    isAway: false,
    propType: "Tournament Winner",
    line: 0,
    direction: "Over",
    pickLabel: "Jon Rahm to win",
    edge: 1.2,
    hitRate: 30,
    confidence: 30,
    reasoning: "Rahm is still a hammer at Augusta when the all-around game is stable. DataGolf rank #2, strong major-winning profile, and +900 is a playable number for a golfer with true win equity. This is not a blind name bet, it is a talent-and-course ceiling bet on one of the few players who can just be the best guy in the field.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: 900,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  },
  {
    id: "golf-scottie-scheffler-tournament-winner-2026-04-09",
    date,
    type: "player",
    playerName: "Scottie Scheffler",
    team: "SCH",
    teamColor: "#167c45",
    opponent: "Masters Tournament",
    isAway: false,
    propType: "Tournament Winner",
    line: 0,
    direction: "Over",
    pickLabel: "Scottie Scheffler to win",
    edge: 1,
    hitRate: 38,
    confidence: 38,
    reasoning: "Scottie is the best golfer in the field, full stop. DataGolf rank #1 and the broadest top-end outcome set at Augusta. The number is short at +510, so this is not sexy, but if you are building a serious Masters win card you do not leave out the most likely winner just because the price is annoying.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: 510,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  },
  {
    id: "golf-bryson-dechambeau-tournament-winner-2026-04-09",
    date,
    type: "player",
    playerName: "Bryson DeChambeau",
    team: "DEC",
    teamColor: "#167c45",
    opponent: "Masters Tournament",
    isAway: false,
    propType: "Tournament Winner",
    line: 0,
    direction: "Over",
    pickLabel: "Bryson DeChambeau to win",
    edge: 0.6,
    hitRate: 28,
    confidence: 28,
    reasoning: "Bryson gives you raw win volatility with enough ceiling to matter at Augusta. DataGolf rank #11 undersells the nuclear version of him when driver and putter spike together. +1050 is live enough to include as the aggressive outright rather than reaching for clown picks with no actual path.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: 1050,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  },
  {
    id: "golf-xander-schauffele-top-5-finish-2026-04-09",
    date,
    type: "player",
    playerName: "Xander Schauffele",
    team: "SCH",
    teamColor: "#167c45",
    opponent: "Masters Tournament",
    isAway: false,
    propType: "Top 5 Finish",
    line: 5,
    direction: "Under",
    pickLabel: "Xander Schauffele Top 5 Finish",
    edge: 2.8,
    hitRate: 46,
    confidence: 46,
    reasoning: "If you want the cleaner Xander exposure, this is it. DataGolf Top 5 probability sits around 18.1%, and +305 implies 24.7%, so it is not some giant math edge, but his consistency at elite events makes this a more stable way to attack him than all-out winner exposure alone.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: 305,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  },
  {
    id: "golf-rory-mcilroy-top-10-finish-2026-04-09",
    date,
    type: "player",
    playerName: "Rory McIlroy",
    team: "MCI",
    teamColor: "#167c45",
    opponent: "Masters Tournament",
    isAway: false,
    propType: "Top 10 Finish",
    line: 10,
    direction: "Under",
    pickLabel: "Rory McIlroy Top 10 Finish",
    edge: 3.2,
    hitRate: 54,
    confidence: 54,
    reasoning: "Rory Top 10 is the adult version of betting Rory. The win can always get weird here, but his ceiling is obvious and DataGolf still gives him a strong top-10 path. At +108 you are getting plus money on one of the few guys who can contend from the jump without needing a miracle week.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: 108,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  },
  {
    id: "golf-patrick-reed-top-10-finish-2026-04-09",
    date,
    type: "player",
    playerName: "Patrick Reed",
    team: "REE",
    teamColor: "#167c45",
    opponent: "Masters Tournament",
    isAway: false,
    propType: "Top 10 Finish",
    line: 10,
    direction: "Under",
    pickLabel: "Patrick Reed Top 10 Finish",
    edge: 4.1,
    hitRate: 41,
    confidence: 41,
    reasoning: "Reed is exactly the kind of Augusta-specific bastard you can still back in the right market. The outright ceiling is lower now, but Top 10 at +300 gives room for his course comfort and short-game survival to matter. This is one of the few non-elite names I actually like because the venue fit is real.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: 300,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  },
  {
    id: "golf-russell-henley-top-10-finish-2026-04-09",
    date,
    type: "player",
    playerName: "Russell Henley",
    team: "HEN",
    teamColor: "#167c45",
    opponent: "Masters Tournament",
    isAway: false,
    propType: "Top 10 Finish",
    line: 10,
    direction: "Under",
    pickLabel: "Russell Henley Top 10 Finish",
    edge: 3.5,
    hitRate: 39,
    confidence: 39,
    reasoning: "Henley is a profile bet, not a brand bet. He is tidy enough tee to green to hang around, and +280 for Top 10 is a fair way to back a player whose path is precision and patience instead of fake bomber hype. Good number, sensible exposure.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: 280,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  },
  {
    id: "golf-xander-schauffele-over-matt-fitzpatrick-h2h-2026-04-09",
    date,
    type: "player",
    playerName: "Xander Schauffele",
    team: "SCH",
    teamColor: "#167c45",
    opponent: "Matt Fitzpatrick",
    isAway: false,
    propType: "Tournament Matchup",
    line: 0,
    direction: "Over",
    pickLabel: "Xander Schauffele over Matt Fitzpatrick",
    edge: 5.4,
    hitRate: 59,
    confidence: 59,
    reasoning: "This is a straight profile gap. Xander brings the cleaner all-around ball-striking baseline and higher win equity, and the matchup price is still only -140. If I am playing one Masters head-to-head, this is the first one in the cart.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: -140,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  },
  {
    id: "golf-rory-mcilroy-over-bryson-dechambeau-h2h-2026-04-09",
    date,
    type: "player",
    playerName: "Rory McIlroy",
    team: "MCI",
    teamColor: "#167c45",
    opponent: "Bryson DeChambeau",
    isAway: false,
    propType: "Tournament Matchup",
    line: 0,
    direction: "Over",
    pickLabel: "Rory McIlroy over Bryson DeChambeau",
    edge: 4.7,
    hitRate: 56,
    confidence: 56,
    reasoning: "Rory over Bryson at -110 is the better side for me because the complete tee-to-green week is more repeatable than Bryson’s spike version. Bryson can absolutely beat him, but at near pick'em I trust Rory's four-round floor more.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: -110,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  },
  {
    id: "golf-russell-henley-over-akshay-bhatia-h2h-2026-04-09",
    date,
    type: "player",
    playerName: "Russell Henley",
    team: "HEN",
    teamColor: "#167c45",
    opponent: "Akshay Bhatia",
    isAway: false,
    propType: "Tournament Matchup",
    line: 0,
    direction: "Over",
    pickLabel: "Russell Henley over Akshay Bhatia",
    edge: 4.2,
    hitRate: 55,
    confidence: 55,
    reasoning: "Henley is the steadier fit in a Masters matchup that should reward discipline more than chaos. Bhatia has upside, but Henley is less likely to beat himself over four rounds, and -124 is still playable for that steadier profile.",
    result: "pending",
    units: 1,
    gameId: "401811941",
    odds: -124,
    book: "DraftKings",
    sportsbook: "DraftKings",
    league: "PGA",
  }
];

(async () => {
  const result = await storeDailyPickSlate(picks, {
    date,
    league: "PGA",
    provenance: "original",
    provenanceNote: "Masters 2026 live card replaced with vetted DraftKings picks and blurbs.",
  });

  console.log(JSON.stringify({
    source: result.source,
    slate: result.slate,
    count: result.picks.length,
    picks: result.picks.map((p) => ({ id: p.id, label: p.pickLabel, odds: p.odds, book: p.book }))
  }, null, 2));
})();
