create or replace view public.historical_trends_loader_source_v1 (
  candidate_id,
  canonical_game_id,
  event_id,
  sport,
  league,
  season,
  event_date,
  home_team,
  away_team,
  team_role,
  team_name,
  opponent_name,
  market_type,
  submarket_type,
  market_family,
  market_scope,
  side,
  line,
  odds,
  sportsbook,
  is_favorite,
  is_underdog,
  is_home_team_bet,
  is_away_team_bet,
  is_home_favorite,
  is_away_favorite,
  is_home_underdog,
  is_road_underdog,
  is_road_favorite,
  result,
  graded,
  integrity_status,
  profit_units,
  profit_dollars_10,
  roi_on_10_flat,
  game_total_line,
  over_odds,
  under_odds,
  is_total_over_bet,
  is_total_under_bet,
  is_prime_time,
  broadcast_window,
  is_back_to_back,
  is_divisional_game,
  team_win_pct_pre_game,
  opponent_win_pct_pre_game,
  team_above_500_pre_game,
  opponent_above_500_pre_game,
  previous_game_shutout,
  days_since_previous_game,
  previous_team_role,
  previous_moneyline_result,
  previous_over_result,
  previous_under_result,
  segment_key,
  is_spread_market,
  is_total_market,
  is_moneyline_market,
  trends_build_version
) as
with base_results as (
  select
    fmb.candidate_id,
    fmb.canonical_game_id,
    fmb.event_id,
    fmb.sport,
    fmb.league,
    fmb.season,
    fmb.event_date,
    fmb.home_team,
    fmb.away_team,
    fmb.market_type,
    fmb.submarket_type,
    fmb.market_family,
    fmb.market_scope,
    fmb.side,
    fmb.line,
    fmb.odds,
    fmb.sportsbook,
    fmb.bet_on_home_team,
    fmb.bet_on_away_team,
    fmb.team_role,
    hmr.result,
    hmr.graded,
    hmr.integrity_status,
    hmr.profit_units,
    hmr.profit_dollars_10,
    hmr.roi_on_10_flat
  from public.fact_historical_market_sides_base_v1 fmb
  left join public.historical_market_results_enriched_v1 hmr
    on hmr.candidate_id = fmb.candidate_id
)
select
  br.candidate_id,
  br.canonical_game_id,
  br.event_id,
  br.sport,
  br.league,
  br.season,
  br.event_date,
  br.home_team,
  br.away_team,
  br.team_role,
  case when br.team_role = 'home' then br.home_team when br.team_role = 'away' then br.away_team else null::text end,
  case when br.team_role = 'home' then br.away_team when br.team_role = 'away' then br.home_team else null::text end,
  br.market_type,
  br.submarket_type,
  br.market_family,
  br.market_scope,
  br.side,
  br.line,
  br.odds,
  br.sportsbook,
  null::boolean,
  null::boolean,
  br.bet_on_home_team,
  br.bet_on_away_team,
  null::boolean,
  null::boolean,
  null::boolean,
  null::boolean,
  null::boolean,
  br.result,
  br.graded,
  br.integrity_status,
  br.profit_units,
  br.profit_dollars_10,
  br.roi_on_10_flat,
  null::numeric,
  null::numeric,
  null::numeric,
  null::boolean,
  null::boolean,
  null::boolean,
  null::text,
  null::boolean,
  null::boolean,
  null::numeric,
  null::numeric,
  null::boolean,
  null::boolean,
  null::boolean,
  null::integer,
  null::text,
  null::text,
  null::text,
  null::text,
  case
    when br.market_type ilike '%1q%' or coalesce(br.submarket_type, '') ilike '%1q%' then '1Q'
    when br.market_type ilike '%1h%' or coalesce(br.submarket_type, '') ilike '%1h%' then '1H'
    when br.market_type ilike '%2q%' or coalesce(br.submarket_type, '') ilike '%2q%' then '2Q'
    when br.market_type ilike '%3q%' or coalesce(br.submarket_type, '') ilike '%3q%' then '3Q'
    when br.market_type ilike '%4q%' or coalesce(br.submarket_type, '') ilike '%4q%' then '4Q'
    when br.market_type ilike '%1p%' or coalesce(br.submarket_type, '') ilike '%1p%' then '1P'
    when br.market_type ilike '%2p%' or coalesce(br.submarket_type, '') ilike '%2p%' then '2P'
    when br.market_type ilike '%3p%' or coalesce(br.submarket_type, '') ilike '%3p%' then '3P'
    else null::text
  end,
  case when br.market_type = 'spread' or br.market_type ilike 'spread%' then true else false end,
  case when br.market_type = 'total' or br.market_type ilike 'total%' then true else false end,
  case when br.market_type = 'moneyline' then true else false end,
  'loader_v3_lean'
from base_results br
where br.team_role in ('home', 'away');
